# Generated by Django 5.1.1 on 2024-10-17 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report_feature', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultReportFeatureContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_content', to='report_feature.resultreportfeature')),
            ],
            options={
                'db_table': 'report_feature_content',
            },
        ),
    ]
