# Generated by Django 5.1.1 on 2024-11-04 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0002_alter_accountroletype_roletype"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("regDate", models.DateTimeField(auto_now_add=True)),
                (
                    "account_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.account",
                    ),
                ),
            ],
            options={
                "db_table": "subscription_history",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPaymentInformation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("paymentID", models.CharField(max_length=100)),
                (
                    "history_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscription.subscriptionhistory",
                    ),
                ),
            ],
            options={
                "db_table": "subscription_payment_information",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("JUNIOR", "Junior"),
                            ("SENIOR", "Senior"),
                            ("LEADER", "Leader"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "history_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscription.subscriptionhistory",
                    ),
                ),
            ],
            options={
                "db_table": "subscription_type",
            },
        ),
    ]
