# Generated by Django 5.0.7 on 2024-11-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MeetingRecordingSummary",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=64)),
                ("writer", models.CharField(max_length=32)),
                ("content", models.TextField()),
                ("regDate", models.DateField(auto_now_add=True)),
            ],
            options={
                "db_table": "meeting_recording_summary",
            },
        ),
    ]
