# Generated by Django 5.1.1 on 2024-10-24 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("report", "0002_rename_writer_resultreport_creator"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultReportOverview",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("overview", models.TextField()),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overview",
                        to="report.resultreport",
                    ),
                ),
            ],
            options={
                "db_table": "report_overview",
            },
        ),
    ]
