# Generated by Django 5.1.1 on 2024-10-17 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report', '0002_rename_writer_resultreport_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultReportImprovement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvement', to='report.resultreport')),
            ],
            options={
                'db_table': 'report_improvement',
            },
        ),
    ]
