# Generated by Django 5.1.1 on 2024-10-14 00:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0003_alter_selectionreview_design_and_more"),
        ("review", "0004_rename_feedback_selectionreview_content"),
    ]

    operations = []
