# Generated by Django 5.1.1 on 2024-10-21 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report_completion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultReportCompletionTotal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('detail', models.TextField()),
                ('completion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total', to='report_completion.resultreportcompletion')),
            ],
            options={
                'db_table': 'report_completion_total',
            },
        ),
    ]
