# Generated by Django 5.1.1 on 2024-10-17 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report_skill_set', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultReportSkill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill', models.CharField(max_length=64)),
                ('skillset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='report_skill_set.resultreportskillset')),
            ],
            options={
                'db_table': 'report_skill',
            },
        ),
    ]
