# Generated by Django 5.1.1 on 2024-10-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_team_member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultreportteammember',
            name='department',
            field=models.CharField(default='개발0팀', max_length=64),
            preserve_default=False,
        ),
    ]
